version: '3'

services:

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chatpi
      - POSTGRES_DB=chatpi
      - POSTGRES_PASSWORD=chatpi

  app:
    image: chatpi:latest
    ports:
      - "8080:4000"
    depends_on:
      - db
    env_file: .env.docker
    environment:
      - DB_HOST=db
      - DB_USER=chatpi
      - DB_PASS=chatpi
      - DB_NAME=chatpi
    command: ["./wait-for.sh", "db:5432", "--", "./run.sh"]

volumes:
  db:
