version: '3'

services:

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatpi
      - POSTGRES_PASSWORD=Pw123

  app:
    image: chatpi:latest
    ports:
      - "8080:4000"
    depends_on:
      - db
    env_file: .env.docker
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=pw123
      - DB_NAME=chatpi
    command: ["./wait-for.sh", "db:5432", "--", "./run.sh"]

volumes:
  db:
